### ISSUE TITLE
No white box around axis in Matplotlib

### ISSUE THREAD

**Issue by royzawadzki** [shahinrostami/theme-purple-please#1]
Compare these two plots:

#1 is from this theme
<img width="433" alt="Screen Shot 2019-07-18 at 11 09 00 AM" src="https://user-images.githubusercontent.com/35274679/61481411-17e57380-a94d-11e9-95e6-3bd886c06a8f.png">
#2 is from the out of the box dark mode in Jupyter Lab
<img width="419" alt="Screen Shot 2019-07-18 at 11 09 18 AM" src="https://user-images.githubusercontent.com/35274679/61481412-17e57380-a94d-11e9-9ac9-2f751f6fbc5d.png">

The plot in #1 does not have a white box around the axis for a graph using matplotlib.

**Comment by shahinrostami** [comment]
Hello @royzawadzki. I completely missed this - didn't get any notifications! I'll have a look at fixing it, it's gone unnoticed for me because I use plotly.

**Comment by shahinrostami** [comment]
Hopefully  I've fixed it in the latest commit (also published to npm). Check it out:

<img width="648" alt="Screenshot 2019-10-13 at 00 19 58" src="https://user-images.githubusercontent.com/15690380/66708887-f16a8500-ed4f-11e9-9a1d-9185c93f0ecb.png">

**Comment by royzawadzki** [comment]
Thanks for fixing this!
