### ISSUE TITLE
Jupyter lab 3?

### ISSUE THREAD

**Issue by dkinneyBU** [shahinrostami/theme-purple-please#7]
I absolutely LOVE this theme, but it seems to no longer work with JL3. Any plans to get it updated?

Thanks!
Dave

**Comment by astrolemonade** [comment]
Please do

**Comment by WestedCrean** [comment]
Created a PR https://github.com/shahinrostami/theme-purple-please/pull/10 updating it for JupyterLab 3. 

If you want to get it working right now, you could download from my fork https://github.com/WestedCrean/theme-purple-please/tree/hotfix/jupyter_3 and see development install instructions

**Comment by dkinneyBU** [comment]
@WestedCrean I'm getting the following error when I try to follow your development instructions:

(env) D:\GitHub\theme-purple-please>npm install

> @shahinrostami/theme-purple-please@1.6.0 prepare D:\GitHub\theme-purple-please
> npm run clean && npm run build


> @shahinrostami/theme-purple-please@1.6.0 clean D:\GitHub\theme-purple-please
> rimraf lib && rimraf static && rimraf tsconfig.tsbuildinfo

'rimraf' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shahinrostami/theme-purple-please@1.6.0 clean: `rimraf lib && rimraf static && rimraf tsconfig.tsbuildinfo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @shahinrostami/theme-purple-please@1.6.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2021-04-10T13_42_54_485Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shahinrostami/theme-purple-please@1.6.0 prepare: `npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @shahinrostami/theme-purple-please@1.6.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2021-04-10T13_42_54_509Z-debug.log


I tried to link it anyway, but that didn't work either:

(env) D:\GitHub\theme-purple-please>jupyter labextension link .
An error occured.
ValueError: "D:\GitHub\theme-purple-please" is not a valid npm package
See the log file for details:  C:\Users\David\AppData\Local\Temp\jupyterlab-debug-d59k15b4.log

**Comment by WestedCrean** [comment]
@dkinneyBU Try to install rimraf globally first with `npm i -g rimraf` then try again, had the same issue first

**Comment by dkinneyBU** [comment]
OK, did that, and when I go back to the dev steps and run npm install, I get this...

(base) will@will-caster-pinn: theme-purple-please$ npm install

> @shahinrostami/theme-purple-please@1.6.0 prepare /home/will/theme-purple-please
> npm run clean && npm run build


> @shahinrostami/theme-purple-please@1.6.0 clean /home/will/theme-purple-please
> rimraf lib && rimraf static && rimraf tsconfig.tsbuildinfo


> @shahinrostami/theme-purple-please@1.6.0 build /home/will/theme-purple-please
> tsc

sh: 1: tsc: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! @shahinrostami/theme-purple-please@1.6.0 build: `tsc`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the @shahinrostami/theme-purple-please@1.6.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/will/.npm/_logs/2021-04-16T20_34_12_620Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! @shahinrostami/theme-purple-please@1.6.0 prepare: `npm run clean && npm run build`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the @shahinrostami/theme-purple-please@1.6.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/will/.npm/_logs/2021-04-16T20_34_12_664Z-debug.log

**Comment by dkinneyBU** [comment]
Well I got a little farther but the build still failed during the link step. Don't worry about it, I'll just wait until it's ready for prime time. Thanks for your efforts, they are appreciated.

**Comment by shahinrostami** [comment]
Hello @dkinneyBU @WestedCrean and @cata0309. 

I've been on Jupyter Lab 2 this whole time and just upgraded and seen that it doesn't work! 

For some disappointing reason I did not receive any notifications about this particular issue and its replies - it's been months!

I'll get theme-purple-please updated for Jupyter Lab 3 tomorrow - watch this space 👍 

@dkinneyBU happy to hear you love this theme!

**Comment by shahinrostami** [comment]
Hello again @dkinneyBU @WestedCrean and @cata0309.

I ended up working on it now instead. It's now working and available for Jupyter Lab 3.

Please consider donating with Github Sponsor https://github.com/sponsors/shahinrostami or even check out my latest project https://plotapi.com!

All the best,

Shahin
